# Use a imagem oficial do PHP 8.2
FROM php:8.2

# Atualizar e instalar pacotes necessários
RUN apt-get update && apt-get install -y \
    software-properties-common \
    libzip-dev \
    unzip \
    git \
    npm

# Instalar o npm
RUN npm install npm@latest -g && \
    npm install n -g && \
    n latest

# Instalar extensões
RUN docker-php-ext-install pdo_mysql zip

# Instalar Composer globalmente
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Definir o diretório de trabalho
WORKDIR /var/www/html

# Copiar o script de inicialização do Laravel
COPY init-laravel.sh /var/www/html/init-laravel.sh

# Mudar para usuário root
USER root

# Dar permissão de execução ao arquivo
RUN chmod +x /var/www/html/init-laravel.sh

# Executar o script de inicialização do Laravel
CMD ["/var/www/html/init-laravel.sh"]
